import linear_differential_equations_abstract_spaces_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace linear_differential_equations_abstract_spaces_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end linear_differential_equations_abstract_spaces_theorem_canonical_lane_mathlib
end HautevilleHouse
